name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Enable MySQL
      run: sudo systemctl start mysql.service
    - name: Create MySQL Database
      run: mysql -u root -p root -e 'CREATE DATABASE `positioning_test`;'
    - name: Enable PostgreSQL
      run: sudo systemctl start postgresql.service
    - name: Run the default task
      run: bundle exec rake
