name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, DB ${{ matrix.db }}
    strategy:
      matrix:
        ruby:
          - '3.0.3'
        db:
          - mysql
          - postgresql
    env:
      DB: ${{ matrix.db }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Enable MySQL
      if: ${{ matrix.db == 'mysql' }}
      - run: sudo systemctl start mysql.service
      - run: mysql -u root -proot -e 'CREATE DATABASE `positioning_test`;'
    - name: Enable PostgreSQL
      if: ${{ matrix.db == 'postgresql' }}
      - run: sudo systemctl start postgresql.service
      - run: psql -U postgres -c 'CREATE DATABASE `positioning_test`;'
    - name: Run the default task
      run: bundle exec rake
